import { Inter } from 'next/font/google';
import 'react-tabs/style/react-tabs.css';
import MobileFooter from './components/MobileFooter';
import Nav from './components/Nav';
import SideNav from './components/SideNav';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <div className='flex'>
          <SideNav />
          {children}
        </div>
        <MobileFooter />
      </body>
    </html>
  )
}
